version: '3'
tasks:
  default:
    desc: "task - for check all tasks"
    cmds:
      - task --list-all
  generate:
    desc: "Command code from proto"
    cmds:
      - protoc -I proto proto/scrapper/*.proto --go_out=./gen/go/ --go_opt=paths=source_relative --go-grpc_out=./gen/go/ --go-grpc_opt=paths=source_relative
      - python3 -m grpc_tools.protoc -I proto --python_out=./gen/python/ --grpc_python_out=./gen/python/ proto/scrapper/*.proto

